site_name: Python for Humanists
docs_dir: 'text'
site_dir: 'docs'
nav: 
  - Home: index.md
  - Set-Up:
    - Computers and You: ch1.md
    - A Taste of Python: ch2.md
  - Basic Syntax:
    - Encoding Identity: ch3.md
    - Anatomy of a Script: ch4.md