site_name: Python for Humanists
docs_dir: 'text'
site_dir: 'docs'
nav: 
  - Home: index.md
  - Set-Up:
    - Computers and You: ch1.md
    - A Taste of Python: ch2.md
  - Basic Syntax:
    - Encoding Identity: ch3.md
    - Anatomy of a Script: ch4.md
  - Flow Control:
    - Branching Flow Control: ch5.md
    - Looping Flow Control: ch6.md
  - Data Types:
    - Primitive and Compound: ch7.md
  - Functions:
    - Introduction to Functions: ch8.md
    - Decomposition: ch9.md
    - Blackboxing and Algorithms: ch10.md   
  - Putting things together:
    - Functions and Scope: ch11.md
    - Libraries and Style: ch12.md
     